### ISSUE TITLE
no such type or enum

### ISSUE THREAD

**Issue by devsnek** [googleapis/nodejs-proto-files#165] opened 2019-03-16 01:13 UTC
#### Environment details

  - OS: MacOS 10.14.4 Beta (18E194d)
  - Node.js version: v12.0.0-pre-969c63a0f1deffaaffcf2bec841bd4a7831559c3
  - npm version: 6.6.0
  - `google-proto-files` version: 0.20.0

When I try to load up the embedded assistant proto files, i get an error:

```
Error: no such Type or Enum 'google.type.LatLng' in Type .google.assistant.embedded.v1alpha2.DeviceLocation
    at Type.lookupTypeOrEnum (node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (node_modules/protobufjs/src/field.js:265:94)
    at Type.resolveAll (node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (node_modules/protobufjs/src/root.js:246:43)
    at Object.loadSync (node_modules/@grpc/proto-loader/build/src/index.js:224:16)
```

the code that throws this is:

```js
const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');
const protoFiles = require('google-proto-files');

const embeddedAssistantPB = grpc
  .loadPackageDefinition(protoLoader.loadSync(protoFiles.embeddedAssistant.v1alpha2))
  .google.assistant.embedded.v1alpha2;
```

**Comment by paulmand3l** [comment] 2019-08-03 03:39
+1

**Comment by alexander-fenster** [comment] 2019-08-03 04:12
@paulmand3l @devsnek This really looks like a `protobufjs` bug. I stared at this for some time and could not figure out what's going on. For some reason, it does not see the message `google.type.LatLng` even though there are no apparent errors. Also, regular `protoc` works.

To workaround, make your own copy of the proto file with the `LatLng` message copied into it:

```
message LatLng {
  // The latitude in degrees. It must be in the range [-90.0, +90.0].
  double latitude = 1;

  // The longitude in degrees. It must be in the range [-180.0, +180.0].
  double longitude = 2;
}

message DeviceLocation {
    // Latitude and longitude of device.
    oneof type {
      LatLng coordinates = 1;   // <---- instead of google.type.LatLng
    }
}
```

It will be compatible with the original message (in terms of serialization).

**Comment by paulmand3l** [comment] 2019-08-04 08:58
Figured it out. Or at least figured out a (slightly less messy) workaround.

For whatever reason, protobufjs seems to have trouble with absolute imports (e.g. the line `import "google/type/latlng.proto";` at the top of https://github.com/googleapis/googleapis/blob/master/google/assistant/embedded/v1alpha2/embedded_assistant.proto

The solution is to add the root as an include dir:

```
const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');
const protoFiles = require('google-proto-files');

const protoDir = protoFiles.embeddedAssistant.v1alpha2;
const packageDefinition = protoLoader.loadSync(protoDir, {
  includeDirs: [
    protoFiles.getProtoPath('..')
  ],
});
const packageObject = grpc.loadPackageDefinition(packageDefinition);
const embedded_assistant_pb = packageObject.google.assistant.embedded.v1alpha2;
```

Note that the `'..'` is relative to the protoFiles installation location in `node_modules`, so there's no introduced fragility.

**Comment by paulmand3l** [comment] 2019-08-04 09:46
Ok, but now all the messages within embedded_assistant_pb are loaded as:

```
  AssistRequest: {
    format: 'Protocol Buffer 3 DescriptorProto',
    type: {
      field: [Array],
      nestedType: [],
      enumType: [],
      extensionRange: [],
      extension: [],
      oneofDecl: [Array],
      reservedRange: [],
      reservedName: [],
      name: 'AssistRequest',
      options: null
    },
    fileDescriptorProtos: [
      <Buffer 0a 1e 67 6f 6f 67 6c 65 5f 70 72 6f 74 6f 62 75 66 5f 70 72 6f 74 6f 62 75 66 2e 70 72 6f 74 6f 12 18 67 6f 6f 67 6c 65 2e 70 72 6f 74 6f 62 75 66 2e ... 4171 more bytes>,
      <Buffer 0a 28 67 6f 6f 67 6c 65 5f 61 73 73 69 73 74 61 6e 74 5f 65 6d 62 65 64 64 65 64 5f 76 31 61 6c 70 68 61 32 2e 70 72 6f 74 6f 12 22 67 6f 6f 67 6c 65 ... 2118 more bytes>,
      <Buffer 0a 10 67 6f 6f 67 6c 65 5f 61 70 69 2e 70 72 6f 74 6f 12 0a 67 6f 6f 67 6c 65 2e 61 70 69 22 45 0a 04 48 74 74 70 12 17 0a 05 72 75 6c 65 73 18 01 20 ... 518 more bytes>,
      <Buffer 0a 11 67 6f 6f 67 6c 65 5f 74 79 70 65 2e 70 72 6f 74 6f 12 0b 67 6f 6f 67 6c 65 2e 74 79 70 65 22 2d 0a 06 4c 61 74 4c 6e 67 12 10 0a 08 6c 61 74 69 ... 138 more bytes>
    ]
  },
```

instead of the constructors they were when using grpc.load:

```
  AssistRequest: [Function: Message] {
    encode: [Function],
    decode: [Function],
    decodeDelimited: [Function],
    decode64: [Function],
    decodeHex: [Function],
    decodeJSON: [Function]
  },
```

I realize this almost certainly isn't nodejs-proto-files's fault. Just... wtf.

**Comment by paulmand3l** [comment] 2019-08-04 09:47
(to reproduce)

```
const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');
const protoFiles = require('google-proto-files');

const protoDir = protoFiles.embeddedAssistant.v1alpha2;
const packageDefinition = protoLoader.loadSync(protoDir, {
  includeDirs: [
    protoFiles.getProtoPath('..')
  ],
});
const protoDescriptor = grpc.loadPackageDefinition(packageDefinition);
const eapb = protoDescriptor.google.assistant.embedded.v1alpha2;

const PROTO_ROOT_DIR = protoFiles.getProtoPath('..');
const embedded_assistant_pb = grpc.load({
  root: PROTO_ROOT_DIR,
  file: path.relative(PROTO_ROOT_DIR, protoFiles.embeddedAssistant.v1alpha2)
}).google.assistant.embedded.v1alpha2;

console.log(eapb);
console.log(embedded_assistant_pb);
```

**Comment by alexander-fenster** [comment] 2019-08-04 21:25
I have one more option for you @paulmand3l: compile the protos into JSON statically using `pbjs` tool from `protobufjs` and then load the resulting JSON. Seems like `pbjs` does not suffer from this problem.

Important: make sure you use `pbjs` from `protobufjs` and not the `pbjs` package from `npm` which is totally not what you need.

```
$ npm install protobufjs google-proto-files grpc @grpc/proto-loader
$ npx pbjs -o protos.json -p node_modules/google-proto-files google/assistant/embedded/v1alpha2/embedded_assistant.proto
```

You will get `./protos.json` which can be loaded just like the proto file:

```js
const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');

const embeddedAssistantPB = grpc
  .loadPackageDefinition(protoLoader.loadSync("./protos.json"))
  .google.assistant.embedded.v1alpha2;

console.log(embeddedAssistantPB);
```

Does this workaround work for you?

Just FYI, we're going to switch all the client libraries (`@google-cloud/*` packages) to this way of proto loading (static JSON) quite soon.

**Comment by alexander-fenster** [comment] 2019-11-19 17:06
All client libraries were switched to consuming protos as JSON a while ago. Closing this for now.

**Closed by alexander-fenster** 2019-11-19 17:06 UTC
Labels: :rotating_light:, priority: p2, type: bug

**Comment by Kate6** [comment] 2023-04-17 00:38
I know this is long closed but I thought I'd leave a note here for anyone who runs into this same issue...  I've updated the code to work properly with @grpc/proto-loader.  This mostly consisted of changing the way the "request" object is built in GoogleAssistant.assist...  See [my fork](https://github.com/Kate6/assistant-sdk-nodejs)...
